#!/usr/bin/env python3
"""Fetch Social Media Profiles — Pull your profile data from YouTube, Instagram, TikTok, etc.
Uses ScrapeCreators API (free 100 credits at scrapecreators.com).
"""

import os, json, sys, urllib.request, urllib.error
from datetime import datetime

API_KEY = os.getenv("SCRAPECREATORS_API_KEY", "")
BASE_URL = "https://api.scrapecreators.com/v1"


def fetch(platform, endpoint, params):
    """Make a ScrapeCreators API request."""
    query = "&".join(f"{k}={v}" for k, v in params.items())
    url = f"{BASE_URL}/{platform}/{endpoint}?{query}"
    req = urllib.request.Request(url, headers={"x-api-key": API_KEY})
    try:
        with urllib.request.urlopen(req) as resp:
            return json.loads(resp.read())
    except urllib.error.HTTPError as e:
        body = e.read().decode() if e.fp else ""
        print(f"  Error fetching {platform}/{endpoint}: {e.code} {body[:200]}")
        return None


def fetch_youtube(handle):
    """Fetch YouTube channel profile."""
    print(f"  Fetching YouTube: @{handle}")
    return fetch("youtube", "channel", {"handle": handle})


def fetch_instagram(handle):
    """Fetch Instagram profile."""
    print(f"  Fetching Instagram: @{handle}")
    return fetch("instagram", "profile", {"username": handle})


def fetch_tiktok(handle):
    """Fetch TikTok profile."""
    print(f"  Fetching TikTok: @{handle}")
    return fetch("tiktok", "profile", {"handle": handle})


def format_number(n):
    """Format large numbers (1200 -> 1.2K)."""
    if not n or not isinstance(n, (int, float)):
        return str(n)
    if n >= 1_000_000:
        return f"{n/1_000_000:.1f}M"
    if n >= 1_000:
        return f"{n/1_000:.1f}K"
    return str(n)


def build_report(handle, results):
    """Build a markdown report from the fetched data."""
    lines = [
        f"# Social Media Profile: @{handle}",
        f"*Fetched: {datetime.now().strftime('%Y-%m-%d %H:%M')}*",
        "",
    ]

    for platform, data in results.items():
        if data is None:
            lines.append(f"## {platform.title()}")
            lines.append("Not found or error fetching profile.")
            lines.append("")
            continue

        lines.append(f"## {platform.title()}")
        lines.append("```json")
        lines.append(json.dumps(data, indent=2, default=str)[:3000])
        lines.append("```")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by scripts/fetch-social.py using ScrapeCreators API*")
    return "\n".join(lines)


def main():
    if not API_KEY:
        print("Error: SCRAPECREATORS_API_KEY not set in .env")
        print("Get your free API key at: https://scrapecreators.com")
        print("Then add to .env: SCRAPECREATORS_API_KEY=your_key_here")
        sys.exit(1)

    if len(sys.argv) < 2:
        print("Usage: python3 scripts/fetch-social.py <handle> [platforms]")
        print("")
        print("Examples:")
        print("  python3 scripts/fetch-social.py scalermax")
        print("  python3 scripts/fetch-social.py scalermax youtube,instagram")
        print("  python3 scripts/fetch-social.py mkbhd youtube")
        print("")
        print("Supported platforms: youtube, instagram, tiktok")
        sys.exit(1)

    handle = sys.argv[1].lstrip("@")
    platforms = sys.argv[2].split(",") if len(sys.argv) > 2 else ["youtube", "instagram", "tiktok"]

    fetchers = {
        "youtube": fetch_youtube,
        "instagram": fetch_instagram,
        "tiktok": fetch_tiktok,
    }

    print(f"Fetching social profiles for @{handle}...")
    results = {}
    for platform in platforms:
        platform = platform.strip().lower()
        if platform in fetchers:
            results[platform] = fetchers[platform](handle)
        else:
            print(f"  Skipping unknown platform: {platform}")

    # Save report
    os.makedirs("outputs", exist_ok=True)
    filename = f"outputs/social-profile-{handle}.md"
    report = build_report(handle, results)
    with open(filename, "w") as f:
        f.write(report)

    print(f"\nSaved to {filename}")
    print("Open the file to see your full social media profile data.")


if __name__ == "__main__":
    main()
